config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get '/about', to: 'pages#about'
  get '/projects', to: 'pages#projects'
  get 'downloads/resume' => 'downloads#resume', as: :resume_download
  get 'contact', to: 'contact_form#new'
  post 'contact', to: 'contact_form#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
    def new
        @contact = Contact.new
      end
    
      def create
        @contact = Contact.new(contact_params)
        if @contact.save
          # Send email to the site owner or notify in other ways
          flash[:success] = 'Thank you for your message!'
          redirect_to contact_path
        else
          flash.now[:error] = @contact.errors.full_messages.join(', ')
          render :new
        end
      end
    
      private
    
      def contact_params
        params.permit(:name, :email, :message)
      end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def resume
    file_path = Rails.root.join('public', 'resume.pdf')
    send_file file_path, filename: 'resume.pdf'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact_form/new.html.erb
<%= render :partial => 'partials/navbar' %>
<%= form_with url: contact_path, method: :post do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>
  <%= form.submit 'Send' %>
<% end %>
<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
  <%end%>
<% if flash[:success].present? %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jacob Rees Portfolio</title>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<div class="navbar">
    <div class="nav-container">
    <a class="name-link" href="/">Jacob Rees</a>
        <ul class="nav">
            <li><%= link_to "about", about_path, class:"nav-links" %></li>
            <li><%= link_to "projects", projects_path, class:"nav-links" %></li>
            <li><%= link_to "contact", about_path, class:"nav-links" %></li>
        </ul>
    </div>
        
</div>

app/views/pages/about.html.erb
<%= render :partial => 'partials/navbar' %>

<div class="about-container">
    <%= image_tag("60970452.jpg", class:"profile-img") %>
    <div class="about-me-img-links-wrapper">
    <a href="https://github.com/jacobrees" target="_blank"><svg class="about-me-img-links" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-4.466 19.59c-.405.078-.534-.171-.534-.384v-2.195c0-.747-.262-1.233-.55-1.481 1.782-.198 3.654-.875 3.654-3.947 0-.874-.312-1.588-.823-2.147.082-.202.356-1.016-.079-2.117 0 0-.671-.215-2.198.82-.64-.18-1.324-.267-2.004-.271-.68.003-1.364.091-2.003.269-1.528-1.035-2.2-.82-2.2-.82-.434 1.102-.16 1.915-.077 2.118-.512.56-.824 1.273-.824 2.147 0 3.064 1.867 3.751 3.645 3.954-.229.2-.436.552-.508 1.07-.457.204-1.614.557-2.328-.666 0 0-.423-.768-1.227-.825 0 0-.78-.01-.055.487 0 0 .525.246.889 1.17 0 0 .463 1.428 2.688.944v1.489c0 .211-.129.459-.528.385-3.18-1.057-5.472-4.056-5.472-7.59 0-4.419 3.582-8 8-8s8 3.581 8 8c0 3.533-2.289 6.531-5.466 7.59z"/></svg></a>
    <a href="https://www.linkedin.com/in/jacob-rees/" target="_blank"><svg class="about-me-img-links" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg></a>
    </div>
    <h1>About Me</h1>
    <p class="about-me-text">I'm passionate about creativity and innovation. I believe that technology and design go hand-in-hand, and I constantly strive to bring a fresh, unique perspective to every project I work on. With my diverse skill set, I'm able to create solutions that are both functional and aesthetically pleasing. Whether it's coding, designing, or problem-solving, I approach each task with enthusiasm and a deep appreciation for the craft.</p>
    <p class="about-me-text">My passion lies in frontend web development, where I enjoy designing and building beautiful and intuitive user interfaces. I find it exciting to explore the latest trends and technologies in this field, always seeking to incorporate the most innovative ideas into my projects.</p>
    <p class="about-me-text">When I'm not coding, I love to indulge in my passion for music. Whether it's playing an instrument or listening to my favorite artists, music has always been a source of inspiration and creativity for me.</p>
    <p class="about-me-text">Thank you for taking the time to visit my website. If you have any questions or would like to discuss a potential project, please don't hesitate to get in touch. I look forward to hearing from you!</p>
    <%= link_to 'Download Resume', resume_download_path, class: "resume-btn" %>
</div>
<div class="mobile-padding">
</div>

app/views/pages/home.html.erb
    <div class="canvas-wrapper">
      <canvas id="canvas1"></canvas>
      <h1 class="name-title">Jacob Rees</h1>
      <div class="home-section">
        <%= link_to "about", about_path, class:"home-links"%>
        <%= link_to "projects", projects_path, class:"home-links"%>
        <%= link_to "contact", contact_path, class:"home-links" %>
      </div>
    </div>
    <%= javascript_include_tag("custom-home/home.js")%>

app/views/pages/projects.html.erb
<%= render :partial => 'partials/navbar' %>

<div id="showcase" class="showcase-section">
      <h2 class="showcase-title">Projects</h2>
      <div class="projects-container">
        <div class="project-container">
          <h3 class="project-title">Phaser 3 Game</h3>
          <div class="project-content-container">
            <a target="_blank" href="https://clever-colden-aa2cd5.netlify.app/"
              ><%= image_tag("Space-Dodger.png", alt: "project image", class: "project-img") %></a>

            <div class="project-description-container">
              <div class="project-technologies">
                <p class="project-technology">HTML</p>
                <p class="project-technology">SCSS</p>
                <p class="project-technology">JavaScript</p>
                <p class="project-technology">Phaser 3</p>
                <p class="project-technology">Webpack</p>
                <p class="project-technology">Firebase</p>
              </div>
              <p class="project-description">
                This is a game built in Javascript. The objective of the game is
                to dodge the asteroids and collect the stars. The game was built
                using the Phaser 3 game framework.
              </p>
              <div class="project-links">
                <a
                  class="website-link"
                  target="_blank"
                  href="https://clever-colden-aa2cd5.netlify.app/"
                  >Website</a
                >
                <a
                  class="github-link"
                  target="_blank"
                  href="https://github.com/jacobrees/Phaser-3-Game"
                  >Code/Docs</a
                >
              </div>
            </div>
          </div>
        </div>
        <div class="project-container">
          <h3 class="project-title">To Do List</h3>
          <div class="project-content-container-invert">
            <a target="_blank" href="https://festive-curran-727aff.netlify.app/"
              ><%= image_tag("todo.png", alt: "project image", class: "project-img") %></a>

            <div class="project-description-container">
              <div class="project-technologies">
                <p class="project-technology">HTML</p>
                <p class="project-technology">SCSS</p>
                <p class="project-technology">JavaScript</p>
                <p class="project-technology">Webpack</p>
                <p class="project-technology">Isotope</p>
                <p class="project-technology">localStorage</p>
              </div>
              <p class="project-description">
                This is a to-do list built in Javascript. The main objective of
                the app is to sort your 'todos' in an extremely easy to use way.
                This app also features a lot of animations.
              </p>
              <div class="project-links">
                <a
                  class="website-link"
                  target="_blank"
                  href="https://festive-curran-727aff.netlify.app/"
                  >Website</a
                >
                <a
                  class="github-link"
                  target="_blank"
                  href="https://github.com/jacobrees/To-Do-List"
                  >Code/Docs</a
                >
              </div>
            </div>
          </div>
        </div>
        <div class="project-container">
          <h3 class="project-title">Tic Tac Toe</h3>
          <div class="project-content-container">
            <a
              target="_blank"
              href="https://laughing-clarke-dd842a.netlify.app/"
              ><%= image_tag("TicTacToe.png", alt: "project image", class: "project-img") %></a>
            <div class="project-description-container">
              <div class="project-technologies">
                <p class="project-technology">HTML</p>
                <p class="project-technology">SCSS</p>
                <p class="project-technology">JavaScript</p>
              </div>
              <p class="project-description">
                This project is a basic game of Tic Tac Toe. The goal of the
                project was to build this using Javascript. This game also
                features an AI component that was coded from scratch.
              </p>
              <div class="project-links">
                <a
                  class="website-link"
                  target="_blank"
                  href="https://laughing-clarke-dd842a.netlify.app/"
                  >Website</a
                >
                <a
                  class="github-link"
                  target="_blank"
                  href="https://github.com/jacobrees/Tic-Tac-Toe"
                  >Code/Docs</a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="mobile-padding">
</div>

app/views/partials/_navbar.html.erb
<div class="navbar">
    <div class="nav-container">
    <%= link_to "Jacob Rees", root_path, class:"name-link"%>
        <ul class="nav">
            <li><%= link_to "about", about_path, class:"nav-links" %></li>
            <li><%= link_to "projects", projects_path, class:"nav-links" %></li>
            <li><%= link_to "contact", contact_path, class:"nav-links" %></li>
        </ul>
    </div>
        
</div>